# logfile owner:group mode count size(KiB) when flags pid_file signal
/Users/administrator/apps/polkaswap-indexer/logs/combined-launchd.log administrator:staff 640 5 102400 * C /Users/administrator/apps/polkaswap-indexer/combined.pid 31
